export const products = [
    {
        id: 1,
        name: "Classic White Sneakers",
        category: "Shoes",
        price: 59.99,
        image: "https://nothingnew.com/cdn/shop/files/1024x1024-Men-LowTop-OffWhite-051623-1_1024x1024.jpg?v=1687965435",
        description: "Comfortable and stylish white sneakers for everyday wear.",
        brand: "UrbanStep",
        quantity: 1,
    },
    {
        id: 2,
        name: "Elegant Gold Necklace",
        category: "Jewelry",
        price: 120.00,
        image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=800&q=80",
        description: "18K gold necklace with a minimalist pendant.",
        brand: "LuxeGems",
        quantity: 1,
    },
    {
        id: 3,
        name: "Denim Jacket",
        category: "Clothes",
        price: 75.50,
        image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80",
        description: "Classic blue denim jacket with a modern fit.",
        brand: "BlueWear",
        quantity: 1,
    },
    {
        id: 4,
        name: "Leather Handbag",
        category: "Bags",
        price: 89.99,
        image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80",
        description: "Premium leather handbag with gold accents.",
        brand: "Bagistry",
        quantity: 1,
    },
    {
        id: 5,
        name: "Silk Scarf",
        category: "Accessories",
        price: 35.00,
        image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=800&q=80",
        description: "Soft silk scarf with floral patterns.",
        brand: "SilkyWay",
        quantity: 1,
    },
    {
        id: 6,
        name: "Running Shoes",
        category: "Shoes",
        price: 68.00,
        image: "https://www.inheritco.com/cdn/shop/files/white-classic-low-top-sneakers-shoes-32111917006935.jpg?v=1725673431&width=1920",
        description: "Lightweight running shoes for all terrains.",
        brand: "SprintX",
        quantity: 1,
    },
    {
        id: 7,
        name: "Pearl Earrings",
        category: "Jewelry",
        price: 45.00,
        image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
        description: "Elegant pearl earrings for special occasions.",
        brand: "Pearlina",
        quantity: 1,
    },
    {
        id: 8,
        name: "Canvas Tote Bag",
        category: "Bags",
        price: 22.99,
        image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80",
        description: "Eco-friendly canvas tote bag for daily use.",
        brand: "EcoCarry",
        quantity: 1,
    },
    {
        id: 9,
        name: "Wool Beanie",
        category: "Accessories",
        price: 18.50,
        image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        description: "Warm wool beanie for winter.",
        brand: "CozyHead",
        quantity: 1,
    },
    {
        id: 10,
        name: "Slim Fit T-Shirt",
        category: "Clothes",
        price: 25.00,
        image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        description: "Soft cotton slim fit t-shirt.",
        brand: "FitWear",
        quantity: 1,
    },
    {
        id: 11,
        name: "Chunky Sneakers",
        category: "Shoes",
        price: 79.99,
        image: "https://shoewarehouse.com.au/cdn/shop/articles/White_Sneaker_Blog_Thumbnail.jpg?v=1693455706",
        description: "Trendy chunky sneakers for a bold look.",
        brand: "UrbanStep",
        quantity: 1,
    },
    {
        id: 12,
        name: "Silver Charm Bracelet",
        category: "Jewelry",
        price: 60.00,
        image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3",
        description: "Sterling silver bracelet with unique charms.",
        brand: "Charmify",
        quantity: 1,
    },
    {
        id: 13,
        name: "Mini Crossbody Bag",
        category: "Bags",
        price: 49.99,
        image: "https://images.unsplash.com/photo-1517841905240-472988babdf9",
        description: "Compact crossbody bag for essentials.",
        brand: "Bagistry",
        quantity: 12,
    },
    {
        id: 14,
        name: "Plaid Shirt",
        category: "Clothes",
        price: 32.00,
        image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        description: "Casual plaid shirt for a relaxed style.",
        brand: "PlaidCo",
        quantity: 2,
    },
    {
        id: 15,
        name: "Aviator Sunglasses",
        category: "Accessories",
        price: 40.00,
        image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
        description: "Classic aviator sunglasses with UV protection.",
        brand: "SunGuard",
        quantity: 12,
    },
    {
        id: 16,
        name: "Leather Belt",
        category: "Accessories",
        price: 28.00,
        image: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca",
        description: "Durable leather belt with a sleek buckle.",
        brand: "BuckleUp",
        quantity: 1,
    }
];
// export const products = [
//   {
//     id: 1,
//     name: "Classic White Sneakers",
//     category: "Shoes",
//     price: 59.99,
//     image: "https://images.unsplash.com/photo-1600185366263-3e2f55b92a3f?auto=format&fit=crop&w=800&q=80",
//     description: "Comfortable and stylish white sneakers for everyday wear.",
//     brand: "UrbanStep",
//   },
//   {
//     id: 2,
//     name: "Elegant Gold Necklace",
//     category: "Jewelry",
//     price: 120.0,
//     image: "https://images.unsplash.com/photo-1611078489935-c6b1f4f71e2c?auto=format&fit=crop&w=800&q=80",
//     description: "18K gold necklace with a minimalist pendant.",
//     brand: "LuxeGems",
//   },
//   {
//     id: 3,
//     name: "Denim Jacket",
//     category: "Clothes",
//     price: 75.5,
//     image: "https://images.unsplash.com/photo-1618354691391-6fe2ab18d24a?auto=format&fit=crop&w=800&q=80",
//     description: "Classic blue denim jacket with a modern fit.",
//     brand: "BlueWear",
//   },
//   {
//     id: 4,
//     name: "Leather Handbag",
//     category: "Bags",
//     price: 89.99,
//     image: "https://images.unsplash.com/photo-1593032457868-96e45ca3e2b0?auto=format&fit=crop&w=800&q=80",
//     description: "Premium leather handbag with gold accents.",
//     brand: "Bagistry",
//   },
//   {
//     id: 5,
//     name: "Silk Scarf",
//     category: "Accessories",
//     price: 35.0,
//     image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80",
//     description: "Soft silk scarf with floral patterns.",
//     brand: "SilkyWay",
//   },
//   {
//     id: 6,
//     name: "Running Shoes",
//     category: "Shoes",
//     price: 68.0,
//     image: "https://images.unsplash.com/photo-1596464716121-d876a3ad985f?auto=format&fit=crop&w=800&q=80",
//     description: "Lightweight running shoes for all terrains.",
//     brand: "SprintX",
//   },
//   {
//     id: 7,
//     name: "Pearl Earrings",
//     category: "Jewelry",
//     price: 45.0,
//     image: "https://images.unsplash.com/photo-1600181954370-49d46de0bb90?auto=format&fit=crop&w=800&q=80",
//     description: "Elegant pearl earrings for special occasions.",
//     brand: "Pearlina",
//   },
//   {
//     id: 8,
//     name: "Canvas Tote Bag",
//     category: "Bags",
//     price: 22.99,
//     image: "https://images.unsplash.com/photo-1571902943202-507ec2618e2e?auto=format&fit=crop&w=800&q=80",
//     description: "Eco-friendly canvas tote bag for daily use.",
//     brand: "EcoCarry",
//   },
//   {
//     id: 9,
//     name: "Wool Beanie",
//     category: "Accessories",
//     price: 18.5,
//     image: "https://images.unsplash.com/photo-1618264181419-3507dd8b4f0a?auto=format&fit=crop&w=800&q=80",
//     description: "Warm wool beanie for winter.",
//     brand: "CozyHead",
//   },
//   {
//     id: 10,
//     name: "Slim Fit T-Shirt",
//     category: "Clothes",
//     price: 25.0,
//     image: "https://images.unsplash.com/photo-1618354691808-8a701d1a37c9?auto=format&fit=crop&w=800&q=80",
//     description: "Soft cotton slim fit t-shirt.",
//     brand: "FitWear",
//   },
//   {
//     id: 11,
//     name: "Chunky Sneakers",
//     category: "Shoes",
//     price: 79.99,
//     image: "https://shoewarehouse.com.au/cdn/shop/articles/White_Sneaker_Blog_Thumbnail.jpg?v=1693455706",
//     description: "Trendy chunky sneakers for a bold look.",
//     brand: "UrbanStep",
//   },
//   {
//     id: 12,
//     name: "Silver Charm Bracelet",
//     category: "Jewelry",
//     price: 60.0,
//     image: "https://images.unsplash.com/photo-1632325099325-b31301653f13?auto=format&fit=crop&w=800&q=80",
//     description: "Sterling silver bracelet with unique charms.",
//     brand: "Charmify",
//   },
//   {
//     id: 13,
//     name: "Mini Crossbody Bag",
//     category: "Bags",
//     price: 49.99,
//     image: "https://images.unsplash.com/photo-1581579185169-5f70765c2c71?auto=format&fit=crop&w=800&q=80",
//     description: "Compact crossbody bag for essentials.",
//     brand: "Bagistry",
//   },
//   {
//     id: 14,
//     name: "Plaid Shirt",
//     category: "Clothes",
//     price: 32.0,
//     image: "https://images.unsplash.com/photo-1571867424480-b2f2cf3ed6b4?auto=format&fit=crop&w=800&q=80",
//     description: "Casual plaid shirt for a relaxed style.",
//     brand: "PlaidCo",
//   },
//   {
//     id: 15,
//     name: "Aviator Sunglasses",
//     category: "Accessories",
//     price: 40.0,
//     image: "https://images.unsplash.com/photo-1593964091747-74d36b2337c6?auto=format&fit=crop&w=800&q=80",
//     description: "Classic aviator sunglasses with UV protection.",
//     brand: "SunGuard",
//   },
//   {
//     id: 16,
//     name: "Leather Belt",
//     category: "Accessories",
//     price: 28.0,
//     image: "https://images.unsplash.com/photo-1619014395520-b8ab220a1e36?auto=format&fit=crop&w=800&q=80",
//     description: "Durable leather belt with a sleek buckle.",
//     brand: "BuckleUp",
//   }
// ];
